# Generated by Django 5.2.17 on 2026-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
