# Generated by Django 5.2.17 on 2026-10-03 15:07

import spendroo.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membershipevent',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
