# Generated by Django 5.2.17 on 2026-10-09 19:29

import billing.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('workspaces', '0003_alter_membership_id_alter_membershipevent_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement_mode', models.CharField(choices=[('enforce', 'Enforce: refuse what a plan does not allow'), ('log_only', 'Log only: allow everything, record what would have been refused'), ('off', 'Off: allow everything')], default='enforce', max_length=10)),
                ('grace_days', models.PositiveSmallIntegerField(default=3, help_text='Days a paid plan stays after its period ends, while the store retries the payment.')),
                ('offline_grace_days', models.PositiveSmallIntegerField(default=3, help_text='Days the app trusts its last known plan after expiry while it cannot reach the server.')),
                ('reselect_cooldown_days', models.PositiveSmallIntegerField(default=30, help_text='After a downgrade, how often a user may change which items stay editable.')),
                ('warn_at_percent', models.PositiveSmallIntegerField(default=75, help_text='The app warns once a limit is this full.')),
                ('ads_honeymoon_days', models.PositiveSmallIntegerField(default=7, help_text='No ads for this long after sign-up.')),
                ('ads_placements', models.JSONField(blank=True, default=list, help_text='Screens that may show a banner, for example ["overview", "accounts"].')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'billing settings',
                'verbose_name_plural': 'billing settings',
            },
        ),
        migrations.CreateModel(
            name='BillingSettingsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('enforcement_mode', models.CharField(choices=[('enforce', 'Enforce: refuse what a plan does not allow'), ('log_only', 'Log only: allow everything, record what would have been refused'), ('off', 'Off: allow everything')], default='enforce', max_length=10)),
                ('grace_days', models.PositiveSmallIntegerField(default=3, help_text='Days a paid plan stays after its period ends, while the store retries the payment.')),
                ('offline_grace_days', models.PositiveSmallIntegerField(default=3, help_text='Days the app trusts its last known plan after expiry while it cannot reach the server.')),
                ('reselect_cooldown_days', models.PositiveSmallIntegerField(default=30, help_text='After a downgrade, how often a user may change which items stay editable.')),
                ('warn_at_percent', models.PositiveSmallIntegerField(default=75, help_text='The app warns once a limit is this full.')),
                ('ads_honeymoon_days', models.PositiveSmallIntegerField(default=7, help_text='No ads for this long after sign-up.')),
                ('ads_placements', models.JSONField(blank=True, default=list, help_text='Screens that may show a banner, for example ["overview", "accounts"].')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_days', models.PositiveIntegerField(blank=True, help_text='How long the plan lasts once taken.', null=True, verbose_name='days')),
                ('benefit_amount', models.PositiveIntegerField(blank=True, help_text='Added to this month, once.', null=True, verbose_name='amount')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(help_text='For staff. Not shown to users.', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('priority', models.IntegerField(default=0, help_text='Higher shows first.')),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('plans', 'Users on chosen plans'), ('users', 'Chosen users')], default='everyone', max_length=10)),
                ('joined_after', models.DateTimeField(blank=True, help_text='Only accounts created after this.', null=True)),
                ('joined_before', models.DateTimeField(blank=True, help_text='Only accounts created before this.', null=True)),
                ('kind', models.CharField(choices=[('none', 'Message only'), ('plan', 'A plan for some days'), ('quota', 'Extra quota this month'), ('store_offer', 'A store offer (discount set up in the store)')], default='none', max_length=20)),
                ('auto_apply', models.BooleanField(default=False, help_text='Everyone in the audience gets a plan benefit while the campaign runs, without tapping anything.')),
                ('store_offer_id', models.CharField(blank=True, default='', max_length=100)),
                ('max_claims', models.PositiveIntegerField(blank=True, help_text='Empty means no cap.', null=True)),
                ('claimed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('placements', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=80)),
                ('title_bn', models.CharField(blank=True, default='', max_length=80, verbose_name='title (Bangla)')),
                ('body', models.CharField(blank=True, default='', max_length=240)),
                ('body_bn', models.CharField(blank=True, default='', max_length=240, verbose_name='body (Bangla)')),
                ('cta', models.CharField(blank=True, default='', max_length=30, verbose_name='button')),
                ('cta_bn', models.CharField(blank=True, default='', max_length=30, verbose_name='button (Bangla)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('benefit_days', models.PositiveIntegerField(blank=True, help_text='How long the plan lasts once taken.', null=True, verbose_name='days')),
                ('benefit_amount', models.PositiveIntegerField(blank=True, help_text='Added to this month, once.', null=True, verbose_name='amount')),
                ('slug', models.SlugField(db_index=False, max_length=60)),
                ('name', models.CharField(help_text='For staff. Not shown to users.', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('priority', models.IntegerField(default=0, help_text='Higher shows first.')),
                ('audience', models.CharField(choices=[('everyone', 'Everyone'), ('plans', 'Users on chosen plans'), ('users', 'Chosen users')], default='everyone', max_length=10)),
                ('joined_after', models.DateTimeField(blank=True, help_text='Only accounts created after this.', null=True)),
                ('joined_before', models.DateTimeField(blank=True, help_text='Only accounts created before this.', null=True)),
                ('kind', models.CharField(choices=[('none', 'Message only'), ('plan', 'A plan for some days'), ('quota', 'Extra quota this month'), ('store_offer', 'A store offer (discount set up in the store)')], default='none', max_length=20)),
                ('auto_apply', models.BooleanField(default=False, help_text='Everyone in the audience gets a plan benefit while the campaign runs, without tapping anything.')),
                ('store_offer_id', models.CharField(blank=True, default='', max_length=100)),
                ('max_claims', models.PositiveIntegerField(blank=True, help_text='Empty means no cap.', null=True)),
                ('claimed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('placements', models.JSONField(blank=True, default=list)),
                ('title', models.CharField(max_length=80)),
                ('title_bn', models.CharField(blank=True, default='', max_length=80, verbose_name='title (Bangla)')),
                ('body', models.CharField(blank=True, default='', max_length=240)),
                ('body_bn', models.CharField(blank=True, default='', max_length=240, verbose_name='body (Bangla)')),
                ('cta', models.CharField(blank=True, default='', max_length=30, verbose_name='button')),
                ('cta_bn', models.CharField(blank=True, default='', max_length=30, verbose_name='button (Bangla)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntitlementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('raise', 'At least this (never less than the plan gives)'), ('add', 'Add to what the plan gives'), ('set', 'Exactly this, even if the plan gives more')], default='raise', max_length=5)),
                ('enabled', models.BooleanField(default=True, help_text='For flags.')),
                ('limit', models.PositiveBigIntegerField(blank=True, help_text='For limits and quotas.', null=True)),
                ('unlimited', models.BooleanField(default=False, help_text='For limits and quotas.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Empty means until removed.', null=True)),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntitlementOverrideEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('mode', models.CharField(choices=[('raise', 'At least this (never less than the plan gives)'), ('add', 'Add to what the plan gives'), ('set', 'Exactly this, even if the plan gives more')], default='raise', max_length=5)),
                ('enabled', models.BooleanField(default=True, help_text='For flags.')),
                ('limit', models.PositiveBigIntegerField(blank=True, help_text='For limits and quotas.', null=True)),
                ('unlimited', models.BooleanField(default=False, help_text='For limits and quotas.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Empty means until removed.', null=True)),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+(\\.[a-z0-9_]+)*$', 'Lowercase words joined by dots, like "insights.export".')])),
                ('kind', models.CharField(choices=[('flag', 'Flag (on / off)'), ('limit', 'Limit (how many at once)'), ('quota', 'Quota (how much per month)')], default='flag', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('is_system', models.BooleanField(default=False, editable=False)),
                ('client_visible', models.BooleanField(default=True, help_text='Send this feature to the app.')),
                ('sort', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'key'],
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('limit_hit', 'Limit hit'), ('paywall_view', 'Upgrade screen seen'), ('upgrade_tap', 'Upgrade tapped'), ('redeem', 'Code redeemed'), ('claim', 'Offer claimed'), ('purchase', 'Purchase')], max_length=20)),
                ('feature_key', models.CharField(blank=True, default='', max_length=80)),
                ('plan_code', models.CharField(blank=True, default='', max_length=40)),
                ('origin', models.CharField(default='server', max_length=10)),
                ('enforced', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeepSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=80)),
                ('scope', models.CharField(blank=True, default='', max_length=36)),
                ('object_id', models.UUIDField()),
                ('limit_at_choice', models.PositiveBigIntegerField()),
                ('chosen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('name_bn', models.CharField(blank=True, default='', max_length=60, verbose_name='name (Bangla)')),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('tagline_bn', models.CharField(blank=True, default='', max_length=200, verbose_name='tagline (Bangla)')),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Higher wins when a user holds more than one plan, and counts as an upgrade.')),
                ('is_default', models.BooleanField(default=False, help_text='The plan of everyone without a subscription.')),
                ('is_public', models.BooleanField(default=True, help_text='Shown on the upgrade screen.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans cannot be given out; existing holders keep them.')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='PlanEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.SlugField(db_index=False, max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('name_bn', models.CharField(blank=True, default='', max_length=60, verbose_name='name (Bangla)')),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('tagline_bn', models.CharField(blank=True, default='', max_length=200, verbose_name='tagline (Bangla)')),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Higher wins when a user holds more than one plan, and counts as an upgrade.')),
                ('is_default', models.BooleanField(default=False, help_text='The plan of everyone without a subscription.')),
                ('is_public', models.BooleanField(default=True, help_text='Shown on the upgrade screen.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans cannot be given out; existing holders keep them.')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='For flags.')),
                ('limit', models.PositiveBigIntegerField(blank=True, help_text='For limits and quotas.', null=True)),
                ('unlimited', models.BooleanField(default=False, help_text='For limits and quotas.')),
            ],
            options={
                'ordering': ['feature__sort', 'feature__key'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('enabled', models.BooleanField(default=False, help_text='For flags.')),
                ('limit', models.PositiveBigIntegerField(blank=True, help_text='For limits and quotas.', null=True)),
                ('unlimited', models.BooleanField(default=False, help_text='For limits and quotas.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('play', 'Google Play'), ('app_store', 'App Store'), ('web', 'Web checkout'), ('dev', 'Development')], max_length=20)),
                ('product_id', models.CharField(max_length=100)),
                ('base_plan_id', models.CharField(blank=True, default='', max_length=100)),
                ('offer_id', models.CharField(blank=True, default='', max_length=100)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('pass_30', '30-day pass'), ('pass_365', '365-day pass'), ('lifetime', 'Lifetime')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_days', models.PositiveIntegerField(blank=True, help_text='How long the plan lasts once taken.', null=True, verbose_name='days')),
                ('benefit_amount', models.PositiveIntegerField(blank=True, help_text='Added to this month, once.', null=True, verbose_name='amount')),
                ('code', models.CharField(default=billing.models.generate_promo_code, max_length=40, unique=True)),
                ('note', models.CharField(blank=True, default='', help_text='Who it is for. Not shown to users.', max_length=200)),
                ('kind', models.CharField(choices=[('plan', 'A plan for some days'), ('quota', 'Extra quota this month')], default='plan', max_length=20)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Empty means no cap.', null=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('benefit_days', models.PositiveIntegerField(blank=True, help_text='How long the plan lasts once taken.', null=True, verbose_name='days')),
                ('benefit_amount', models.PositiveIntegerField(blank=True, help_text='Added to this month, once.', null=True, verbose_name='amount')),
                ('code', models.CharField(default=billing.models.generate_promo_code, max_length=40)),
                ('note', models.CharField(blank=True, default='', help_text='Who it is for. Not shown to users.', max_length=200)),
                ('kind', models.CharField(choices=[('plan', 'A plan for some days'), ('quota', 'Extra quota this month')], default='plan', max_length=20)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Empty means no cap.', null=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=60, unique=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('store', 'Store purchase'), ('web_pass', 'Web pass'), ('grant', 'Granted by staff'), ('promo_code', 'Promo code'), ('campaign', 'Campaign'), ('trial', 'Trial')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Empty means it never ends.', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('source', models.CharField(choices=[('store', 'Store purchase'), ('web_pass', 'Web pass'), ('grant', 'Granted by staff'), ('promo_code', 'Promo code'), ('campaign', 'Campaign'), ('trial', 'Trial')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Empty means it never ends.', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=80)),
                ('period', models.CharField(help_text='YYYY-MM, or "lifetime".', max_length=10)),
                ('used', models.PositiveBigIntegerField(default=0)),
                ('bonus', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=80)),
                ('period', models.CharField(max_length=10)),
                ('kind', models.CharField(choices=[('consume', 'Used'), ('top_up', 'Top-up')], default='consume', max_length=10)),
                ('amount', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('ref', models.CharField(blank=True, default='', max_length=200)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, default='', max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='received', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='billingsettings',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_billingsettingsevent" ("ads_honeymoon_days", "ads_placements", "enforcement_mode", "grace_days", "id", "offline_grace_days", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reselect_cooldown_days", "updated_at", "warn_at_percent") VALUES (NEW."ads_honeymoon_days", NEW."ads_placements", NEW."enforcement_mode", NEW."grace_days", NEW."id", NEW."offline_grace_days", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reselect_cooldown_days", NEW."updated_at", NEW."warn_at_percent"); RETURN NULL;', hash='22bc62f40bef827a33a2e662f071c869521b38b8', operation='INSERT', pgid='pgtrigger_insert_insert_9947b', table='billing_billingsettings', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='billingsettings',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_billingsettingsevent" ("ads_honeymoon_days", "ads_placements", "enforcement_mode", "grace_days", "id", "offline_grace_days", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reselect_cooldown_days", "updated_at", "warn_at_percent") VALUES (NEW."ads_honeymoon_days", NEW."ads_placements", NEW."enforcement_mode", NEW."grace_days", NEW."id", NEW."offline_grace_days", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reselect_cooldown_days", NEW."updated_at", NEW."warn_at_percent"); RETURN NULL;', hash='d5ecfe1fe28965fbe3e2cd07c2fed69295932370', operation='UPDATE', pgid='pgtrigger_update_update_e9cc7', table='billing_billingsettings', when='AFTER')),
        ),
        migrations.AddField(
            model_name='billingsettingsevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='billingsettingsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.billingsettings'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignclaim',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='billing.campaign'),
        ),
        migrations.AddField(
            model_name='campaignclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.campaign'),
        ),
        migrations.AddField(
            model_name='entitlementoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementoverrideevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementoverrideevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='entitlementoverrideevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.entitlementoverride'),
        ),
        migrations.AddField(
            model_name='entitlementoverrideevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementoverrideevent',
            name='feature',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.feature'),
        ),
        migrations.AddField(
            model_name='entitlementoverride',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='billing.feature'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='benefit_feature',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'kind': 'quota'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.feature', verbose_name='quota'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='benefit_feature',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'quota'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.feature', verbose_name='quota'),
        ),
        migrations.AddField(
            model_name='funnelevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='keepselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_selections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='one_default_plan'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='benefit_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_plans',
            field=models.ManyToManyField(blank=True, related_name='+', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='benefit_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan', verbose_name='plan'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plan',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_planevent" ("code", "created_at", "id", "is_active", "is_default", "is_public", "name", "name_bn", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rank", "sort", "tagline", "tagline_bn", "updated_at") VALUES (NEW."code", NEW."created_at", NEW."id", NEW."is_active", NEW."is_default", NEW."is_public", NEW."name", NEW."name_bn", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rank", NEW."sort", NEW."tagline", NEW."tagline_bn", NEW."updated_at"); RETURN NULL;', hash='bf84a192b8be84f75adf9c0b0d3c8e6acc71cc9a', operation='INSERT', pgid='pgtrigger_insert_insert_85755', table='billing_plan', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='plan',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_planevent" ("code", "created_at", "id", "is_active", "is_default", "is_public", "name", "name_bn", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rank", "sort", "tagline", "tagline_bn", "updated_at") VALUES (NEW."code", NEW."created_at", NEW."id", NEW."is_active", NEW."is_default", NEW."is_public", NEW."name", NEW."name_bn", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rank", NEW."sort", NEW."tagline", NEW."tagline_bn", NEW."updated_at"); RETURN NULL;', hash='949058d5bcccbf1d2b9b43e9ce6187e1ab811786', operation='UPDATE', pgid='pgtrigger_update_update_586bc', table='billing_plan', when='AFTER')),
        ),
        migrations.AddField(
            model_name='planevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='planevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_values', to='billing.feature'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='planfeatureevent',
            name='feature',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.feature'),
        ),
        migrations.AddField(
            model_name='planfeatureevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='planfeatureevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.planfeature'),
        ),
        migrations.AddField(
            model_name='planfeatureevent',
            name='plan',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='product',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='benefit_feature',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'quota'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.feature', verbose_name='quota'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='benefit_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to='billing.campaign'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocode',
            name='only_plans',
            field=models.ManyToManyField(blank=True, help_text='Only users currently on one of these. Empty means anyone.', related_name='+', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='promocodeevent',
            name='benefit_feature',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'kind': 'quota'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.feature', verbose_name='quota'),
        ),
        migrations.AddField(
            model_name='promocodeevent',
            name='benefit_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.plan', verbose_name='plan'),
        ),
        migrations.AddField(
            model_name='promocodeevent',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.campaign'),
        ),
        migrations.AddField(
            model_name='promocodeevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promocodeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='promocodeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.promocode'),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.promocode'),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.campaign'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.product'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.promocode'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='campaignclaim',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.campaign'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='plan',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.plan'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.product'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='promo_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='billing.promocode'),
        ),
        migrations.AddField(
            model_name='subscriptionevent',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagecounter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='billingevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='one_event_per_provider_id'),
        ),
        migrations.AddIndex(
            model_name='entitlementoverride',
            index=models.Index(fields=['user'], name='billing_ent_user_id_8267d7_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entitlementoverride',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_entitlementoverrideevent" ("created_at", "created_by_id", "enabled", "ends_at", "feature_id", "id", "limit", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "starts_at", "unlimited", "user_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."enabled", NEW."ends_at", NEW."feature_id", NEW."id", NEW."limit", NEW."mode", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason", NEW."starts_at", NEW."unlimited", NEW."user_id"); RETURN NULL;', hash='255b66de13fd7b4af61dd05c64bd13a07a83923c', operation='INSERT', pgid='pgtrigger_insert_insert_6dda1', table='billing_entitlementoverride', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entitlementoverride',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_entitlementoverrideevent" ("created_at", "created_by_id", "enabled", "ends_at", "feature_id", "id", "limit", "mode", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "starts_at", "unlimited", "user_id") VALUES (NEW."created_at", NEW."created_by_id", NEW."enabled", NEW."ends_at", NEW."feature_id", NEW."id", NEW."limit", NEW."mode", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason", NEW."starts_at", NEW."unlimited", NEW."user_id"); RETURN NULL;', hash='3530671c14b574cee6800a39d5c1609633e8ebe0', operation='UPDATE', pgid='pgtrigger_update_update_79f29', table='billing_entitlementoverride', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='funnelevent',
            index=models.Index(fields=['kind', 'created_at'], name='billing_fun_kind_c03c95_idx'),
        ),
        migrations.AddConstraint(
            model_name='keepselection',
            constraint=models.UniqueConstraint(fields=('user', 'feature_key', 'scope', 'object_id'), name='one_keep_per_object'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='campaign',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_campaignevent" ("audience", "auto_apply", "benefit_amount", "benefit_days", "benefit_feature_id", "benefit_plan_id", "body", "body_bn", "claimed_count", "created_at", "created_by_id", "cta", "cta_bn", "ends_at", "id", "is_active", "joined_after", "joined_before", "kind", "max_claims", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "placements", "priority", "slug", "starts_at", "store_offer_id", "title", "title_bn", "updated_at") VALUES (NEW."audience", NEW."auto_apply", NEW."benefit_amount", NEW."benefit_days", NEW."benefit_feature_id", NEW."benefit_plan_id", NEW."body", NEW."body_bn", NEW."claimed_count", NEW."created_at", NEW."created_by_id", NEW."cta", NEW."cta_bn", NEW."ends_at", NEW."id", NEW."is_active", NEW."joined_after", NEW."joined_before", NEW."kind", NEW."max_claims", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."placements", NEW."priority", NEW."slug", NEW."starts_at", NEW."store_offer_id", NEW."title", NEW."title_bn", NEW."updated_at"); RETURN NULL;', hash='f3c7195a38cbf979533be1f1e9f11bd7bb796900', operation='INSERT', pgid='pgtrigger_insert_insert_0ae1a', table='billing_campaign', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='campaign',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_campaignevent" ("audience", "auto_apply", "benefit_amount", "benefit_days", "benefit_feature_id", "benefit_plan_id", "body", "body_bn", "claimed_count", "created_at", "created_by_id", "cta", "cta_bn", "ends_at", "id", "is_active", "joined_after", "joined_before", "kind", "max_claims", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "placements", "priority", "slug", "starts_at", "store_offer_id", "title", "title_bn", "updated_at") VALUES (NEW."audience", NEW."auto_apply", NEW."benefit_amount", NEW."benefit_days", NEW."benefit_feature_id", NEW."benefit_plan_id", NEW."body", NEW."body_bn", NEW."claimed_count", NEW."created_at", NEW."created_by_id", NEW."cta", NEW."cta_bn", NEW."ends_at", NEW."id", NEW."is_active", NEW."joined_after", NEW."joined_before", NEW."kind", NEW."max_claims", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."placements", NEW."priority", NEW."slug", NEW."starts_at", NEW."store_offer_id", NEW."title", NEW."title_bn", NEW."updated_at"); RETURN NULL;', hash='0f0e65dd9e653ee0d63571774f22f9ad57a94546', operation='UPDATE', pgid='pgtrigger_update_update_ab32b', table='billing_campaign', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='one_value_per_plan_feature'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='planfeature',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_planfeatureevent" ("enabled", "feature_id", "id", "limit", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "unlimited") VALUES (NEW."enabled", NEW."feature_id", NEW."id", NEW."limit", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plan_id", NEW."unlimited"); RETURN NULL;', hash='1653cd0212ff58c16bec219afee1011568b5f0df', operation='INSERT', pgid='pgtrigger_insert_insert_c3dc8', table='billing_planfeature', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='planfeature',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_planfeatureevent" ("enabled", "feature_id", "id", "limit", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "unlimited") VALUES (NEW."enabled", NEW."feature_id", NEW."id", NEW."limit", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plan_id", NEW."unlimited"); RETURN NULL;', hash='c58ec07a507169626e899338cbb28e779069dec4', operation='UPDATE', pgid='pgtrigger_update_update_44422', table='billing_planfeature', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('provider', 'product_id', 'base_plan_id'), name='one_product_per_store_id'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='promocode',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_promocodeevent" ("benefit_amount", "benefit_days", "benefit_feature_id", "benefit_plan_id", "campaign_id", "code", "created_at", "created_by_id", "ends_at", "id", "is_active", "kind", "max_redemptions", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redeemed_count", "starts_at") VALUES (NEW."benefit_amount", NEW."benefit_days", NEW."benefit_feature_id", NEW."benefit_plan_id", NEW."campaign_id", NEW."code", NEW."created_at", NEW."created_by_id", NEW."ends_at", NEW."id", NEW."is_active", NEW."kind", NEW."max_redemptions", NEW."note", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."redeemed_count", NEW."starts_at"); RETURN NULL;', hash='eeb7073c568c61ca2616c7661fafc9fe6134e284', operation='INSERT', pgid='pgtrigger_insert_insert_918b4', table='billing_promocode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='promocode',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_promocodeevent" ("benefit_amount", "benefit_days", "benefit_feature_id", "benefit_plan_id", "campaign_id", "code", "created_at", "created_by_id", "ends_at", "id", "is_active", "kind", "max_redemptions", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "redeemed_count", "starts_at") VALUES (NEW."benefit_amount", NEW."benefit_days", NEW."benefit_feature_id", NEW."benefit_plan_id", NEW."campaign_id", NEW."code", NEW."created_at", NEW."created_by_id", NEW."ends_at", NEW."id", NEW."is_active", NEW."kind", NEW."max_redemptions", NEW."note", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."redeemed_count", NEW."starts_at"); RETURN NULL;', hash='101d1403ef8e8cf325fc104c9e26516e139c6830', operation='UPDATE', pgid='pgtrigger_update_update_1e13c', table='billing_promocode', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='billing_sub_user_id_fe5b98_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'external_id'), name='one_subscription_per_external_id'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subscription',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "billing_subscriptionevent" ("campaign_id", "cancel_at_period_end", "created_at", "created_by_id", "current_period_end", "external_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "product_id", "promo_code_id", "provider", "reason", "source", "starts_at", "status", "updated_at", "user_id") VALUES (NEW."campaign_id", NEW."cancel_at_period_end", NEW."created_at", NEW."created_by_id", NEW."current_period_end", NEW."external_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."plan_id", NEW."product_id", NEW."promo_code_id", NEW."provider", NEW."reason", NEW."source", NEW."starts_at", NEW."status", NEW."updated_at", NEW."user_id"); RETURN NULL;', hash='c753977348ede1bc0090984e9e00dbe0a0f0c219', operation='INSERT', pgid='pgtrigger_insert_insert_6f62d', table='billing_subscription', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='subscription',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "billing_subscriptionevent" ("campaign_id", "cancel_at_period_end", "created_at", "created_by_id", "current_period_end", "external_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "plan_id", "product_id", "promo_code_id", "provider", "reason", "source", "starts_at", "status", "updated_at", "user_id") VALUES (NEW."campaign_id", NEW."cancel_at_period_end", NEW."created_at", NEW."created_by_id", NEW."current_period_end", NEW."external_id", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."plan_id", NEW."product_id", NEW."promo_code_id", NEW."provider", NEW."reason", NEW."source", NEW."starts_at", NEW."status", NEW."updated_at", NEW."user_id"); RETURN NULL;', hash='83d95311c6c7b3e62e9cecc01b976661722753c4', operation='UPDATE', pgid='pgtrigger_update_update_5c2d2', table='billing_subscription', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='promoredemption',
            constraint=models.UniqueConstraint(fields=('promo_code', 'user'), name='one_redemption_per_user_per_code'),
        ),
        migrations.AddConstraint(
            model_name='campaignclaim',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='one_claim_per_user_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.UniqueConstraint(fields=('user', 'feature_key', 'period'), name='one_counter_per_user_feature_period'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'feature_key', 'period'], name='billing_usa_user_id_64bb5a_idx'),
        ),
    ]
