# Generated by Django 5.2.17 on 2026-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='primary_mode',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('business', 'Business')], default='', max_length=10),
        ),
    ]
