# Generated by Django 5.2.17 on 2026-10-09 06:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0003_dedupe_usernames_case_insensitive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='appuser_username_ci_unique'),
        ),
    ]
