# Generated by Django 5.2.17 on 2026-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_server_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncmutation',
            name='error_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
