# Generated by Django 5.2.4 on 2025-10-12 16:16

import cashbooks.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Book',
                'verbose_name_plural': 'Cash Books',
            },
        ),
        migrations.CreateModel(
            name='CashBookAdditionalMember',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cashbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbooks.cashbook')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Book External Member',
                'verbose_name_plural': 'Cash Book External Members',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('Cash In', 'cash_in'), ('Cash Out', 'cash_out')], default='cash_in', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbooks.cashbookadditionalmember')),
                ('cashbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbooks.cashbook')),
            ],
            options={
                'verbose_name': 'Cashbook Entry',
                'verbose_name_plural': 'Cashbook Entries',
            },
        ),
        migrations.CreateModel(
            name='EntryBills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bill_file', models.FileField(upload_to=cashbooks.models.get_user_bill_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Please upload a valid file. Allowed formats are: %(allowed_extensions)s')])),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbooks.entry')),
            ],
            options={
                'verbose_name': 'Bill of Entry',
                'verbose_name_plural': 'Bills of Entries',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbooks.cashbook')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbooks.paymentmethod'),
        ),
        migrations.CreateModel(
            name='EntryCategory',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbooks.cashbook')),
            ],
            options={
                'verbose_name': 'Entry Category',
                'verbose_name_plural': 'Entry Categories',
                'indexes': [models.Index(fields=['cashbook', 'category_name'], name='cashbooks_e_cashboo_0f9af7_idx'), models.Index(fields=['created_at'], name='cashbooks_e_created_4b9f37_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntryExtraFields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbooks.entry')),
            ],
            options={
                'verbose_name': 'Extra Field of Entry',
                'verbose_name_plural': 'Extra Fields of Entries',
                'indexes': [models.Index(fields=['entry', 'field_name'], name='cashbooks_e_entry_i_ff6dbe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['cashbook', 'payment_method_name'], name='cashbooks_p_cashboo_c14df1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['created_at'], name='cashbooks_p_created_050cd2_idx'),
        ),
    ]
