# Generated by Django 5.2.4 on 2025-10-17 05:36

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbook',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cash Book', 'verbose_name_plural': 'Cash Books'},
        ),
        migrations.AlterModelOptions(
            name='cashbookadditionalmember',
            options={'ordering': ['-added_at'], 'verbose_name': 'Cash Book Additional Member', 'verbose_name_plural': 'Cash Book Additional Members'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-entry_date', '-timestamp'], 'verbose_name': 'Cashbook Entry', 'verbose_name_plural': 'Cashbook Entries'},
        ),
        migrations.AlterModelOptions(
            name='entrybills',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Bill of Entry', 'verbose_name_plural': 'Bills of Entries'},
        ),
        migrations.AlterModelOptions(
            name='entrycategory',
            options={'ordering': ['category_name'], 'verbose_name': 'Entry Category', 'verbose_name_plural': 'Entry Categories'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['payment_method_name'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='additional_member',
        ),
        migrations.AddField(
            model_name='cashbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 17, 5, 35, 49, 762316, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbooks.entrycategory'),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(default=datetime.date(2025, 10, 17)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entrybills',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 17, 5, 36, 31, 670994, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashbookadditionalmember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashbookadditionalmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], default='cash_out', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrybills',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='cashbooks.entry'),
        ),
        migrations.AlterField(
            model_name='entrybills',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrycategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entryextrafields',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='cashbooks.entry'),
        ),
        migrations.AlterField(
            model_name='entryextrafields',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='cashbookadditionalmember',
            unique_together={('cashbook', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='entrycategory',
            unique_together={('cashbook', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('cashbook', 'payment_method_name')},
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['cashbook', 'entry_date'], name='cashbooks_e_cashboo_318945_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entry_type'], name='cashbooks_e_entry_t_4fc46b_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_by'], name='cashbooks_e_created_a7c592_idx'),
        ),
    ]
