# Generated by Django 5.2.4 on 2025-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbooks', '0002_alter_cashbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='entrycategory',
            index=models.Index(fields=['is_deleted'], name='cashbooks_e_is_dele_692582_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_deleted'], name='cashbooks_p_is_dele_cb9b90_idx'),
        ),
    ]
