# Generated by Django 5.2.17 on 2026-10-02 20:00

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0002_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='cashbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmemberevent',
            name='added_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmemberevent',
            name='cashbook',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmemberevent',
            name='member',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmemberevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmemberevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='cashbook.cashbookadditionalmember'),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmemberevent',
            name='workspace',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='cashbookevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbookevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='cashbookevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='cashbookevent',
            name='workspace',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='entry',
            name='cashbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='entrybills',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='cashbook.entry'),
        ),
        migrations.AddField(
            model_name='entrybills',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='cashbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbook.entrycategory'),
        ),
        migrations.AddField(
            model_name='entrycategoryevent',
            name='cashbook',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='entrycategoryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='entrycategoryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='cashbook.entrycategory'),
        ),
        migrations.AddField(
            model_name='entrycategoryevent',
            name='workspace',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='cashbook',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cashbook.entrycategory'),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='cashbook.entry'),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='workspace',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='entryextrafields',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='cashbook.entry'),
        ),
        migrations.AddField(
            model_name='entryextrafields',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cashbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='workspace',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='payment_method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cashbook.paymentmethod'),
        ),
        migrations.AddField(
            model_name='entry',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbook.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentmethodevent',
            name='cashbook',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='cashbook.cashbook'),
        ),
        migrations.AddField(
            model_name='paymentmethodevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='paymentmethodevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='cashbook.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentmethodevent',
            name='workspace',
            field=models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='cashbook',
            index=models.Index(fields=['workspace', 'created_at'], name='cashbook_ca_workspa_38a8e1_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbook',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_cashbookevent" ("book_name", "created_at", "created_by_id", "currency", "deleted_at", "description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "version", "workspace_id") VALUES (NEW."book_name", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='75e734df21806b23cc1a1150cc70924dde3780a0', operation='INSERT', pgid='pgtrigger_insert_insert_96f66', table='cashbook_cashbook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbook',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_cashbookevent" ("book_name", "created_at", "created_by_id", "currency", "deleted_at", "description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "version", "workspace_id") VALUES (NEW."book_name", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='32289d33c8aa711ee46174c48a2a972731a6b38a', operation='UPDATE', pgid='pgtrigger_update_update_48a84', table='cashbook_cashbook', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='cashbookadditionalmember',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cashbook', 'member'), name='one_grant_per_member_per_cashbook'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbookadditionalmember',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_cashbookadditionalmemberevent" ("added_by_id", "cashbook_id", "created_at", "deleted_at", "id", "member_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "updated_at", "version", "workspace_id") VALUES (NEW."added_by_id", NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."member_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='ac5450d6b2ff6611ac3fc1cce331ce2621ab2800', operation='INSERT', pgid='pgtrigger_insert_insert_664fc', table='cashbook_cashbookadditionalmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbookadditionalmember',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_cashbookadditionalmemberevent" ("added_by_id", "cashbook_id", "created_at", "deleted_at", "id", "member_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "updated_at", "version", "workspace_id") VALUES (NEW."added_by_id", NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."member_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='96d5f78e8304409d65937772933732ef0e9cab2a', operation='UPDATE', pgid='pgtrigger_update_update_52178', table='cashbook_cashbookadditionalmember', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='entrycategory',
            index=models.Index(fields=['workspace', 'cashbook', 'category_name'], name='cashbook_en_workspa_12a4c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entrycategory',
            unique_together={('cashbook', 'category_name')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entrycategory',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_entrycategoryevent" ("cashbook_id", "category_name", "created_at", "deleted_at", "id", "is_default", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."category_name", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='c97e7327b089a73e532acb556435163aef5e5428', operation='INSERT', pgid='pgtrigger_insert_insert_bfb91', table='cashbook_entrycategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entrycategory',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_entrycategoryevent" ("cashbook_id", "category_name", "created_at", "deleted_at", "id", "is_default", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."category_name", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='c1b928a61e9cdbef887708ad48b155f1c08daefc', operation='UPDATE', pgid='pgtrigger_update_update_03600', table='cashbook_entrycategory', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='entryextrafields',
            index=models.Index(fields=['entry', 'field_name'], name='cashbook_en_entry_i_79637b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['workspace', 'cashbook', 'payment_method_name'], name='cashbook_pa_workspa_568f5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('cashbook', 'payment_method_name')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='paymentmethod',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_paymentmethodevent" ("cashbook_id", "created_at", "deleted_at", "id", "is_default", "payment_method_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", NEW."payment_method_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='8191e30ce7ed6083c50088bde958c247ba9b34fc', operation='INSERT', pgid='pgtrigger_insert_insert_72601', table='cashbook_paymentmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='paymentmethod',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_paymentmethodevent" ("cashbook_id", "created_at", "deleted_at", "id", "is_default", "payment_method_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", NEW."payment_method_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='028f1e9f0dd5a703fbfa85e4fdebe97983062f16', operation='UPDATE', pgid='pgtrigger_update_update_0fa87', table='cashbook_paymentmethod', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['workspace', 'cashbook', 'entry_date'], name='cashbook_en_workspa_37acb1_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['entry_type'], name='cashbook_en_entry_t_cd0f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['created_by'], name='cashbook_en_created_3023e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='entry_amount_positive'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_entryevent" ("amount_minor", "cashbook_id", "category_id", "created_at", "created_by_id", "currency", "deleted_at", "entry_date", "entry_type", "id", "payment_method_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remarks", "source", "title", "updated_at", "version", "workspace_id") VALUES (NEW."amount_minor", NEW."cashbook_id", NEW."category_id", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."entry_date", NEW."entry_type", NEW."id", NEW."payment_method_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."remarks", NEW."source", NEW."title", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='d9a848ea16a93a4925c961dc087d6481c7d4249e', operation='INSERT', pgid='pgtrigger_insert_insert_cc4c0', table='cashbook_entry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_entryevent" ("amount_minor", "cashbook_id", "category_id", "created_at", "created_by_id", "currency", "deleted_at", "entry_date", "entry_type", "id", "payment_method_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remarks", "source", "title", "updated_at", "version", "workspace_id") VALUES (NEW."amount_minor", NEW."cashbook_id", NEW."category_id", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."entry_date", NEW."entry_type", NEW."id", NEW."payment_method_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."remarks", NEW."source", NEW."title", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='b813df4498089ec8e8ea3b9233e3685a2db7224d', operation='UPDATE', pgid='pgtrigger_update_update_e7420', table='cashbook_entry', when='AFTER')),
        ),
    ]
