# Generated by Django 5.2.17 on 2026-10-02 20:14

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0004_row_level_security'),
        ('workspaces', '0002_workspace_is_demo'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashbook',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashbook',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashbookadditionalmember',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cashbookadditionalmember',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='entry',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='entry',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='entrycategory',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='entrycategory',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='paymentmethod',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='paymentmethod',
            name='update_update',
        ),
        migrations.AlterUniqueTogether(
            name='entrycategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmember',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cashbookadditionalmemberevent',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cashbookevent',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='entrybills',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='entrycategoryevent',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='entryevent',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='entryextrafields',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='paymentmethodevent',
            name='server_seq',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbook',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_cashbookevent" ("book_name", "created_at", "created_by_id", "currency", "deleted_at", "description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."book_name", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='769789c2e5d1bba2a9b1249cce3ee767e2afc751', operation='INSERT', pgid='pgtrigger_insert_insert_96f66', table='cashbook_cashbook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbook',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_cashbookevent" ("book_name", "created_at", "created_by_id", "currency", "deleted_at", "description", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."book_name", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."description", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='b413d8b0284ebb74449c92f24113a72cec19ea58', operation='UPDATE', pgid='pgtrigger_update_update_48a84', table='cashbook_cashbook', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbookadditionalmember',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_cashbookadditionalmemberevent" ("added_by_id", "cashbook_id", "created_at", "deleted_at", "id", "member_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."added_by_id", NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."member_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='163eb7a4a66dc1acf49ccf9173753ac0a66a7dd2', operation='INSERT', pgid='pgtrigger_insert_insert_664fc', table='cashbook_cashbookadditionalmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cashbookadditionalmember',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_cashbookadditionalmemberevent" ("added_by_id", "cashbook_id", "created_at", "deleted_at", "id", "member_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."added_by_id", NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."member_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='739d37d71369665b88a58701df1cc026bff754fd', operation='UPDATE', pgid='pgtrigger_update_update_52178', table='cashbook_cashbookadditionalmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entry',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_entryevent" ("amount_minor", "cashbook_id", "category_id", "created_at", "created_by_id", "currency", "deleted_at", "entry_date", "entry_type", "id", "payment_method_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remarks", "server_seq", "source", "title", "updated_at", "version", "workspace_id") VALUES (NEW."amount_minor", NEW."cashbook_id", NEW."category_id", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."entry_date", NEW."entry_type", NEW."id", NEW."payment_method_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."remarks", NEW."server_seq", NEW."source", NEW."title", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='f97a653217fc809f2d55b5ba313c49b469e94aee', operation='INSERT', pgid='pgtrigger_insert_insert_cc4c0', table='cashbook_entry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entry',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_entryevent" ("amount_minor", "cashbook_id", "category_id", "created_at", "created_by_id", "currency", "deleted_at", "entry_date", "entry_type", "id", "payment_method_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "remarks", "server_seq", "source", "title", "updated_at", "version", "workspace_id") VALUES (NEW."amount_minor", NEW."cashbook_id", NEW."category_id", NEW."created_at", NEW."created_by_id", NEW."currency", NEW."deleted_at", NEW."entry_date", NEW."entry_type", NEW."id", NEW."payment_method_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."remarks", NEW."server_seq", NEW."source", NEW."title", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='d62f73f29f6b5a30b26049259401227d7d5b9bc7', operation='UPDATE', pgid='pgtrigger_update_update_e7420', table='cashbook_entry', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entrycategory',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_entrycategoryevent" ("cashbook_id", "category_name", "created_at", "deleted_at", "id", "is_default", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."category_name", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='2dc9b92cac36c5c529f81c9d6caccae2ffac55c9', operation='INSERT', pgid='pgtrigger_insert_insert_bfb91', table='cashbook_entrycategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entrycategory',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_entrycategoryevent" ("cashbook_id", "category_name", "created_at", "deleted_at", "id", "is_default", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."category_name", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='65d82649a9a6e18b4688eec7cc0921e10fb075c1', operation='UPDATE', pgid='pgtrigger_update_update_03600', table='cashbook_entrycategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='paymentmethod',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_paymentmethodevent" ("cashbook_id", "created_at", "deleted_at", "id", "is_default", "payment_method_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", NEW."payment_method_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='f1bfa9b389204c04846dfef75427da2b055b0738', operation='INSERT', pgid='pgtrigger_insert_insert_72601', table='cashbook_paymentmethod', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='paymentmethod',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_paymentmethodevent" ("cashbook_id", "created_at", "deleted_at", "id", "is_default", "payment_method_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", NEW."payment_method_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='0ed869344a5bb8fc7560f36c2dfb140c9ebb59e8', operation='UPDATE', pgid='pgtrigger_update_update_0fa87', table='cashbook_paymentmethod', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='entrycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cashbook', 'category_name'), name='one_category_name_per_cashbook'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cashbook', 'payment_method_name'), name='one_payment_method_name_per_cashbook'),
        ),
    ]
