# Generated by Django 5.2.17 on 2026-10-03 15:07

import spendroo.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0006_sync_cursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashbookadditionalmember',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashbookadditionalmemberevent',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='cashbookevent',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrybills',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrycategory',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrycategoryevent',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='entryevent',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, serialize=False),
        ),
        migrations.AlterField(
            model_name='entryextrafields',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethodevent',
            name='id',
            field=models.UUIDField(default=spendroo.ids.uuid7, editable=False, serialize=False),
        ),
    ]
