# Generated by Django 5.2.17 on 2026-10-09 19:29

import cashbook.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0007_alter_cashbook_id_alter_cashbookadditionalmember_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrybills',
            name='size_bytes',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='entrybills',
            name='bill_file',
            field=models.FileField(max_length=300, upload_to=cashbook.models.get_user_bill_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Please upload a valid file. Allowed formats are: %(allowed_extensions)s')]),
        ),
    ]
