# Generated by Django 5.2.17 on 2026-10-10 08:10

import django.core.validators
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0008_entrybills_size_bytes_alter_entrybills_bill_file'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='entrycategory',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='entrycategory',
            name='update_update',
        ),
        migrations.AddField(
            model_name='entrycategory',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}\\Z', 'Enter a colour as #RRGGBB.')]),
        ),
        migrations.AddField(
            model_name='entrycategoryevent',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}\\Z', 'Enter a colour as #RRGGBB.')]),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entrycategory',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "cashbook_entrycategoryevent" ("cashbook_id", "category_name", "color", "created_at", "deleted_at", "id", "is_default", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."category_name", NEW."color", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='defd7466804b8b04828a5852b2fb03d97f3ef191', operation='INSERT', pgid='pgtrigger_insert_insert_bfb91', table='cashbook_entrycategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='entrycategory',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "cashbook_entrycategoryevent" ("cashbook_id", "category_name", "color", "created_at", "deleted_at", "id", "is_default", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "updated_at", "version", "workspace_id") VALUES (NEW."cashbook_id", NEW."category_name", NEW."color", NEW."created_at", NEW."deleted_at", NEW."id", NEW."is_default", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."server_seq", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='db84426011ef6899ee31a7a3264319adeb5d687c', operation='UPDATE', pgid='pgtrigger_update_update_03600', table='cashbook_entrycategory', when='AFTER')),
        ),
    ]
