# Generated by Django 5.2.17 on 2026-10-02 20:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('operation', models.TextField(blank=True, help_text='Optional description for the action', null=True)),
                ('model_name', models.CharField(max_length=1000)),
                ('record_ids', models.TextField(blank=True, help_text='ID of the records being modified', null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON representation of the changes made', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CRUD Log',
                'verbose_name_plural': 'CRUD Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
