# Generated by Django 5.2.17 on 2026-10-02 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crudlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crud_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='crudlog',
            index=models.Index(fields=['user'], name='audit_crudl_user_id_8b38fb_idx'),
        ),
        migrations.AddIndex(
            model_name='crudlog',
            index=models.Index(fields=['action'], name='audit_crudl_action_d169b0_idx'),
        ),
        migrations.AddIndex(
            model_name='crudlog',
            index=models.Index(fields=['model_name'], name='audit_crudl_model_n_988d28_idx'),
        ),
        migrations.AddIndex(
            model_name='crudlog',
            index=models.Index(fields=['timestamp'], name='audit_crudl_timesta_42bd9d_idx'),
        ),
    ]
