# Generated by Django 5.2.4 on 2025-10-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='is_business_profile',
        ),
    ]
