# Generated by Django 5.2.4 on 2025-08-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Template name (e.g: auth_signup)', max_length=100, unique=True),
        ),
    ]
