# Generated by Django 5.2.4 on 2025-08-22 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manager', '0002_emaillog_sender_email_alter_emailtemplate_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=20)),
                ('operation', models.TextField(blank=True, help_text='Optional description for the action', null=True)),
                ('model_name', models.CharField(max_length=1000)),
                ('record_ids', models.TextField(blank=True, help_text='ID of the records being modified', null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON representation of the changes made', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crud_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRUD Log',
                'verbose_name_plural': 'CRUD Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='system_mana_user_id_94dbdb_idx'), models.Index(fields=['action'], name='system_mana_action_5296d4_idx'), models.Index(fields=['model_name'], name='system_mana_model_n_55c25d_idx'), models.Index(fields=['timestamp'], name='system_mana_timesta_45c307_idx')],
            },
        ),
    ]
