# Generated by Django 5.2.17 on 2026-10-02 20:14

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('workspaces', '0002_workspace_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('server_seq', models.BigIntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('savings', 'Savings'), ('mobile_money', 'Mobile money'), ('card', 'Card')], default='cash', max_length=20)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('opening_balance_minor', models.BigIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('server_seq', models.BigIntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('server_seq', models.BigIntegerField(default=0, editable=False)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], default='expense', max_length=10)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(editable=False, max_length=3)),
                ('transfer_group_id', models.UUIDField(blank=True, null=True)),
                ('occurred_on', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sms', 'SMS'), ('email', 'Email'), ('upload', 'Statement upload'), ('ai', 'AI')], default='manual', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ledger_personal.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger_personal.category')),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('server_seq', models.BigIntegerField(default=0, editable=False)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], default='expense', max_length=10)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(editable=False, max_length=3)),
                ('transfer_group_id', models.UUIDField(blank=True, null=True)),
                ('occurred_on', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('sms', 'SMS'), ('email', 'Email'), ('upload', 'Statement upload'), ('ai', 'AI')], default='manual', max_length=10)),
                ('account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='ledger_personal.account')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='ledger_personal.category')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='ledger_personal.transaction')),
                ('workspace', models.ForeignKey(db_constraint=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('server_seq', models.BigIntegerField(default=0, editable=False)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('workspace', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='ledger_personal.category')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='budget_amount_positive'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('category',), name='one_budget_per_category')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['workspace', 'account', 'occurred_on'], name='ledger_pers_workspa_319cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['workspace', 'category', 'occurred_on'], name='ledger_pers_workspa_aaa6a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor', 0), _negated=True), name='transaction_amount_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_minor__lt', 0), ('kind', 'expense'), ('transfer_group_id__isnull', True)), models.Q(('amount_minor__gt', 0), ('kind', 'income'), ('transfer_group_id__isnull', True)), models.Q(('kind', 'transfer'), ('transfer_group_id__isnull', False)), _connector='OR'), name='transaction_sign_matches_kind'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transaction',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "ledger_personal_transactionevent" ("account_id", "amount_minor", "category_id", "created_at", "currency", "deleted_at", "id", "kind", "note", "occurred_on", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "source", "transfer_group_id", "updated_at", "version", "workspace_id") VALUES (NEW."account_id", NEW."amount_minor", NEW."category_id", NEW."created_at", NEW."currency", NEW."deleted_at", NEW."id", NEW."kind", NEW."note", NEW."occurred_on", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."server_seq", NEW."source", NEW."transfer_group_id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='5a0345066053a6a9244ab429cbef83feacc96603', operation='INSERT', pgid='pgtrigger_insert_insert_69d85', table='ledger_personal_transaction', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transaction',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "ledger_personal_transactionevent" ("account_id", "amount_minor", "category_id", "created_at", "currency", "deleted_at", "id", "kind", "note", "occurred_on", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "server_seq", "source", "transfer_group_id", "updated_at", "version", "workspace_id") VALUES (NEW."account_id", NEW."amount_minor", NEW."category_id", NEW."created_at", NEW."currency", NEW."deleted_at", NEW."id", NEW."kind", NEW."note", NEW."occurred_on", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."server_seq", NEW."source", NEW."transfer_group_id", NEW."updated_at", NEW."version", NEW."workspace_id"); RETURN NULL;', hash='21b45dd638c3c81db4493928be3bf3401a59f84f', operation='UPDATE', pgid='pgtrigger_update_update_cf2bb', table='ledger_personal_transaction', when='AFTER')),
        ),
    ]
