# Generated by Django 5.2.17 on 2026-10-03 15:07

import casharoo.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_personal', '0002_rls_and_sync_cursor'),
        ('workspaces', '0003_alter_membership_id_alter_membershipevent_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='one_budget_per_category',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=casharoo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.UUIDField(default=casharoo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=casharoo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=casharoo.ids.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionevent',
            name='id',
            field=models.UUIDField(default=casharoo.ids.uuid7, editable=False, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('month__isnull', True), ('month__day', 1), _connector='OR'), name='budget_month_first_day'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('month__isnull', True)), fields=('category',), name='one_recurring_budget_per_category'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('month__isnull', False)), fields=('category', 'month'), name='one_budget_per_category_month'),
        ),
    ]
