# Generated by Django 5.2.17 on 2026-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_personal', '0003_remove_budget_one_budget_per_category_budget_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
