# Generated by Django 5.2.17 on 2026-10-10 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_personal', '0005_mark_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}\\Z', 'Enter a colour as #RRGGBB.')]),
        ),
    ]
