# Generated by Django 5.2.17 on 2026-10-02 20:00

import casharoo.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this email account', max_length=100)),
                ('email_address', models.EmailField(help_text='Email address to send from', max_length=100)),
                ('smtp_server', models.CharField(help_text='SMTP server address', max_length=100)),
                ('smtp_port', models.IntegerField(default=465, help_text='SMTP server port')),
                ('username', models.CharField(blank=True, help_text='SMTP username', max_length=100, null=True)),
                ('password', casharoo.fields.EncryptedTextField(help_text='SMTP password, stored encrypted (Use app password for gmail accounts!)')),
                ('use_tls', models.BooleanField(default=False, help_text='Use TLS for connection')),
                ('use_ssl', models.BooleanField(default=True, help_text='Use SSL for connection')),
                ('is_active', models.BooleanField(default=True, help_text='Is this account active?')),
                ('purpose', models.CharField(choices=[('default', 'Default'), ('marketing', 'Marketing Emails'), ('transactional', 'Transactional Emails'), ('notification', 'Notification Emails'), ('support', 'Support Emails'), ('auth', 'Authentication'), ('no-reply', 'No Reply'), ('other', 'Other')], help_text='Email purpose', max_length=20)),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_emails', models.TextField()),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('purpose', models.CharField(default='default', max_length=100)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (e.g: auth_signup)', max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Email subject', max_length=200)),
                ('body_text', models.TextField(help_text='Plain text email body')),
                ('body_html', models.TextField(blank=True, help_text='HTML email body', null=True)),
                ('purpose', models.CharField(choices=[('default', 'Default'), ('marketing', 'Marketing Emails'), ('transactional', 'Transactional Emails'), ('notification', 'Notification Emails'), ('support', 'Support Emails'), ('auth', 'Authentication'), ('other', 'Other')], help_text='Template purpose', max_length=20)),
            ],
        ),
    ]
